### ISSUE TITLE
Create cleaner versions of the examples in the admin page.

### ISSUE THREAD

**Issue by davmillar** [davmillar/DavesMapper#42]
Using the existing images as a guide, create cleaner explanatory images to take their places:
- images/nminfo1.png
- images/svinfo1.png
- images/svinfo2.png
- images/svinfo3.png

**Comment by paurisa** [comment]
I'm cleaning the images, I've already done 2 of them but before continuing I want to know if they are correct.

![nminfo](https://cloud.githubusercontent.com/assets/7051536/19498318/7d630778-9590-11e6-8883-b3c489fcdef4.png)
![svinfo1](https://cloud.githubusercontent.com/assets/7051536/19498317/7d5d40a4-9590-11e6-940f-949ba09555e1.png)

Should I clean the other 2?

**Comment by davmillar** [comment]
That's close, but ideally the numbers on the edges should match the number of grid squares like in the original.

**Comment by paurisa** [comment]
Got it! Will fix it and clean the other 2.

**Comment by paurisa** [comment]
Is this better?
![svinfo1](https://cloud.githubusercontent.com/assets/7051536/19520092/30e6939a-960f-11e6-9d78-a6059464d465.png)

**Comment by davmillar** [comment]
Looking good!

**Comment by davmillar** [comment]
And thanks, BTW :)

**Comment by paurisa** [comment]
Hope you like them! And no problem 👍
