### ISSUE TITLE
Move keyboard shortcuts to a modal in the main app.

### ISSUE THREAD

**Issue by davmillar** [davmillar/DavesMapper#49]
Keyboard shortcuts are currently listed at the top of the help page. Ideally they should be moved to an in-app modal invoked by the question mark (?) key. The modal should reuse some of the code used for the intro popup. A nice-to-have would be to make that modal code even more reusable.

**Comment by cjbagley** [comment]
Hi there!

I'd like to maybe give this a go if possible? Could you just confirm how you where thinking of having this: do you mean that there would be a question mark somewhere on the page, and if so, where are you thinking?

**Comment by davmillar** [comment]
I was thinking it would come up when the question mark key on the keyboard
is pressed, kind of like on GitHub itself. I hadn't thought of any visual
cue for that yet, but I'm open to any ideas you have.

**Comment by cjbagley** [comment]
That sounds good to me! Sorry - first time contributing to something, so might be stupid questions, but I've forked and cloned the repo locally: is there anything I need to run to get it setup, as it's just showing a blank page save for two links to 'blog' and 'about us'. Also - I've had a little dig around an notice it's running some queries to a database, which I don't have a copy of: will I be able to get it to run without?

Thanks in advance :)

**Comment by davmillar** [comment]
You will need the database to have it run. I'm not sure if I left good
enough info in the repo to have that ready to go, but I'll check it tonight
and see if I can create a sanitized dump for running it locally. Sorry! I'm
kinda new to dev ops type stuff myself.
